image: alpine

before_script:
  - apt-get update -qq && apt-get install -y -qq openjdk-8-jdk
  - apt-get install ant
  
stages:
  - compile

compile:
  stage: compile
  artifacts:
    paths:
      - BrinoIDE.jar
  script:
    - ant
  only:
  - ODB
